# coding: utf-8
__author__ = 'Insality'

GAME_TITLE = 'Argalatic'
GAME_WIDTH = 1024
GAME_HEIGHT = 384

ENTITY_ENEMY = 0
ENTITY_ENEMY_BULLET = 1
ENTITY_PLAYER = 2
ENTITY_PLAYER_BULLET = 3
ENTITY_UNDEFINED = 4
ENTITY_FROGBOSS_BULLET = 5